name: Publishing

on:
  workflow_dispatch:
  push:
    tags:
      - '*'

jobs:

  build-sdist:
    name: Build source tarball
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - run: |
          python -m pip install --upgrade build
          python -m build --sdist
      - uses: actions/upload-artifact@v4
        with:
          path: ./dist/*

  build-wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04]
    env:
      CIBW_BUILD: cp310-manylinux_x86_64
    steps:
      - uses: actions/checkout@v3

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.20.0
      - uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-${{ matrix.os }}-${{ strategy.job-index }}
          path: ./wheelhouse/*.whl

  publish:
    name: Publish on PyPI
    environment: 
      name: publishing_to_pypi
      url: https://pypi.org/p/dependency-injector-fg
    needs: [build-sdist, build-wheels]
    runs-on: ubuntu-22.04
    permissions:
      id-token: write
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: dist
          merge-multiple: true
      - uses: pypa/gh-action-pypi-publish@release/v1
